require('./administrador.module.js');
//require('./administrador.controller');
require('./administrador.service');
require('./citas/_citas');
require('./clientes/_clientes');
require('./add_mecanico/add_mecanico');
require('./mantenimientos/_mantenimientos');
//require('./autos/_autos');
require('./admin/_admin');